_docs-v4/event-model/event-parsing.md
Some very minor typoes I found while perusing your v4 docs
=> Typo fixes

_docs-v4/business-hours/businessHours-per-resource.md
Updated to v4 and included daysOfWeek in example
=> Update businessHours-per-resource to new api

_docs-v3/date-library/date-library.md, _docs-v3/date-library/defaultRangeSeparator.md, _docs-v3/toolbar/titleRangeSeparator.md, _docs-v3/toolbar/toolbar.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/3200
=> [DA] iss-3200: document titleRangeSeparator

_docs-v1/event-dragging-resizing/editable.md, _docs-v3/event-display/background-events.md, _docs-v3/event-dragging-resizing/editable.md, _docs-v4/event-display/background-events.md, _docs-v4/event-dragging-resizing/editable.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4902
=> [DA] iss-4902: background events can't be dragged or resized

_docs-v4/event-model/event-parsing.md, _docs-v4/event-model/recurring-events.md
https://github.com/fullcalendar/fullcalendar/issues/4573
=> Issue 4573: event parsing

_docs-v3/event-data/event-object.md, _docs-v4/event-model/event-object.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4542
=> Issue 4542: event object article

_docs-v4/resource-data/resource-data.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4278
=> [DA] events > resources

_docs-v3/view-api/view-object.md, _docs-v4/view-api/view-object.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4879
=> [DA] issue-4879: start/end dates can be changed on view object

_docs-v3/event-data/event-object.md, _docs-v4/event-model/event-object.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4887
Not sure how to format **requires premium**
=> [DA] iss-4887: document resourceids property in event object

_docs-v4/custom-views/visibleRange.md
Updated for FCv4 compatibility by removing moment date manipulation methods and replacing them with native JS Date object manipulation methods.
=> Removed Moment date manipulations, replaced with pure JS

_docs-v3/event-display/eventAfterRender.md, _docs-v4/event-display/eventPositioned.md, _docs-v4/event-display/eventRender.md
https://github.com/fullcalendar/fullcalendar/issues/2706
=> [DA] Docs for eventRender/eventAfterRender, make clear that they are called once for each segment

_docs-v1/intro/usage.md, _docs-v3/custom-views/custom-view-with-js.md, _docs-v3/intro/intro.md, _docs-v4/custom-views/custom-view-with-js.md, _docs-v4/intro/intro.md
=> [DA] principals > principles

_docs-v4/business-hours/businessHours-per-resource.md, _docs-v4/business-hours/businessHours.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4948
=> [DA] business hours may be an array

_docs-v4/custom-views/visibleRange.md, _docs-v4/sizing/aspectRatio.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4985
=> [DA] iss-4985: remove .option() calls

_docs-v4/event-model/event-object.md, _docs-v4/event-model/event-parsing.md, _docs-v4/event-popover/eventLimitClick.md, _docs-v4/event-source/endParam.md, _docs-v4/event-source/events-function.md, _docs-v4/resource-data/resources-function.md, _docs-v4/view-api/view-object.md
https://github.com/fullcalendar/fullcalendar/issues/3205
=> [DA] iss03205: inclusive and exclusive dates and events

README.md, _docs-v1/event-dragging-resizing/editable.md, _docs-v4/date-clicking-selecting/Calendar-select.md, _docs-v4/date-clicking-selecting/select-callback.md, _docs-v4/event-display/background-events.md, _docs-v4/event-display/nextDayThreshold.md, _docs-v4/event-model/event-object.md, _docs-v4/event-model/event-parsing.md, _docs-v4/event-source/events-function.md, _docs-v4/list-view/list-view.md, _docs-v4/view-api/view-object.md
Fixed: fullcalendar/fullcalendar#3393
=> [DA] issue-3393 and changes to make linting happy

_docs-v4/event-model/recurring-events.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4779
@arshaw Would this be more complete with code samples at the bottom of this page?
=> [DA] recurrent events can be grouped together for interactions

_docs-v4/event-display/background-events.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/5009
=> [DA] Inverse background docs refers to events that share the same id 

_docs-v3/custom-views/custom-view-with-js.md, _docs-v4/custom-views/custom-view-with-js.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/4146
=> [DA] issue #4146: custom view doc update

_docs-v4/event-source/events-json-feed.md
Ticket: https://github.com/fullcalendar/fullcalendar/issues/1042
=> [DA] issue-1042: document date format in json feeds

_docs-v4/custom-views/duration.md
Issue: https://github.com/fullcalendar/fullcalendar/issues/3659
=> [DA] clarify setting duration dynamically

_docs-v5/event-display/event-render-hooks.md
complete the properties "view"
=> complete the properties "view"

_docs-v4/third-party/vue.md
Just started using full calendar plugin and came against an issue that the callbacks were not firing. found this answer to the issue here.
https://stackoverflow.com/questions/56261140/dateclick-not-emitted-in-fullcalendar-angular
i thought other people might come against this problem when doing the demo. Coped the text from the fullcalendar docs.
=> Update vue.md Including the interactions plugin

_docs-v5/resource-display/resourceOrder.md
https://github.com/fullcalendar/fullcalendar/issues/5587
=> 5587 - resourceOrder docs mentions old default

_docs-v5/upgrading-from-v4.md
I hope this isn't too much of a nit pick. The old description had a few spelling errors, and I felt it was quite wordy. I think the simplified description is much clearer.
=> Shorten duration description and fix some minor English errors

_docs-v5/sizing/aspectRatio.md
=> Correct a spelling mistake.

_docs-v6/third-party/angular.md
add missing interactionPlugin while using dateClick method
=> docs: update v6 Angular Component page

_docs-v6/event-dragging-resizing/eventConstraint.md
Issue in the documentation with unmatching keys with the event api
=> Update eventConstraint.md fix start-end range

_docs-v6/third-party/react.md
This updated markdown includes code snippets that utilize React's functional components and hooks.
=> Updated React Component Markdown to utilize React's functional components and hooks.
