fullcalendar/fullcalendar-docs

_docs-v3/deprecated/jquery-ui-dnd.md

Issue https://github.com/fullcalendar/fullcalendar/issues/3849
This is edited to mention the necessary use of an external library to enable Touch Support.

Mention external touch library support

---

_docs-v3/timeline-view/timeline-view.md

Fix a typo in documentation : using `[ .. ]` instead of `{ .. }`

Typo in TimeLine view configuration

---

_docs-v4/custom-views/custom-view-with-js.md

It seems the property is actually called 'views' not 'viewConfigs'.
The example doesn't work as it is.

viewConfigs doesn't work

---

_docs-v4/event-dragging-resizing/eventDragStop.md
_docs-v4/event-dragging-resizing/eventResizeStop.md

The following screenshot shows the callback start/end dates, when I resized an event from 10am-11am to 10am-12:30pm.

Fix eventDragStop and eventResizeStop docs: callback info is *before* changes

---

_docs-v4/event-source/event-source-object.md

Version 4.x of the docs uses the old version of the event function signature

Event Source Object :: wrong signature for event function

---

_docs-v4/event-model/Calendar-addEvent.md

Just fixing a minor typo that I encountered while trying to understand Fullcalendar. Great work!

Removed doubled 'the'

---

_docs-v4/event-model/rrule-plugin.md

As suggested in https://github.com/fullcalendar/fullcalendar-site-static/pull/109, it might be a good idea to clarify the handling of basic and extended date and date-times. Users that have to write their own parser to comply with what Fullcalendar understands in contrast to what RFC5545 defines might find this information rather usefull.

Added some clarification on ISO8601 dates

---

_docs-v4/date-library/date-parsing.md

Users of Fullcalendar can run into the issue that they try parsing ICS date-time data that uses the basic format. In theses cases the format has to be parsed to the extended format as this is the only format accepted by Fullcalendar.

Added some clarification on ISO8601 strings

---

_docs-v5/date-library/Calendar-formatIso.md

In the documentation, the method formatIso had a typo.

Document correction : canlendar.formatIso method

---

_docs-v4/third-party/vue.md

For V5 you have renamed the file from fullcalendar-options.js to options.js 
https://github.com/fullcalendar/fullcalendar-vue/commit/ab777e39aefd1bd0cc822bf7fbf5ce1d43043ca2#diff-25d902c24283ab8cfbac54dfa101ad31
Currently using V4.4 myself

Update vue.md update options.js link

---

_docs-v4/event-model/rrule-plugin.md

As far as I know, dtstart is usually a date-time. When it is a date only, it should be interpreted as an all-day event. This is also, what I found working with ICS data so far. See also: https://tools.ietf.org/html/rfc5545#section-3.8.2.4

Fixed an factual error at dtstart and added notes on extended ISO8601 date format

---

_docs-v5/sizing/updateSize.md

It was pretty challenging to figure out where the method was located when the docs just say `.updateSize()`, especially if you are using the React library. It is already a little tricky to figure out how to access the Calendar API.

Update updateSize doc to clarify location

---

_docs-v5/date-library/Calendar-formatRange.md

While reading the documentation I noticed that calendar.formatDate is used and it should be calendar.formatRange
here is the change:
<div class='spec' markdown='1'>
calendar.formatRange( *start*, *end*, *settings* )
</div>

formatRange instead of formatDate

---

_docs-v5/resource-data/resource-parsing.md

Change:
An alternative method for specify
To:
An alternative method for specifying

Change 'specify' to 'specifying' - minor grammar edit

---

_docs-v5/date-library/moment-timezone-plugin.md

This page is for the moment timezone plugin but was referencing the fullcalendar moment plugin (same url as the moment plugin doc page).

Fix fullcalendar moment-timezone script src

---

README.md
_includes/docs-controls/edit-button.html

Hi,
Fixes [#6807](https://github.com/fullcalendar/fullcalendar/issues/6807)
For this PR, I:
- Fix broken link for edit button, by replacing the main branch by `main`, because it seems that the main branch of your documentation has changed.
- I also took the opportunity to change the name of the main contribution branch in the README

[Docs] Button "edit doc" link is broken

---

_docs-v5/timegrid-view/eventShortHeight.md
_docs-v6/timegrid-view/eventShortHeight.md

Currently, the document does not have `img` rendered. This PR fixes the problem.

Adds closing brackets to fix broken markdown contents

---

_docs-v5/intro/content-injection.md
_docs-v6/intro/content-injection.md

The content injection page does not seem to be in the same place in the v4 docs? If it's moved I didn't find it, if it's new in v5 then no earlier pages would need updating.

typo: unescapted -> unescaped

---

_docs-v6/custom-views/custom-view-with-js.md

Descriptions of the custom views with JavaScript should at least include a simple reference to the `didMount` and `willUnmount` methods that are invoked when the custom view has just loaded or is about to be unloaded, respectively. I had to go digging in the test cases to find that these event existed and they seem a common use case.

Include `didMount` and `willUnmount` in documented example.

---

_docs-v6/timegrid-view/all-day-render-hooks.md

Just came across this while trying to do some custom styling using the timeGridWeek view and copied the same description format for the 'el' property from the Day-Cell Render Hooks page.

Adding view and el properties to All-Day Render Hooks

---

_docs-v6/third-party/angular.md

In my personal opinion, it's better to use an arrow function as a call-back then directly passing in a function and using .bind(this) to keep the scope. Arrow functions are now widely known and provide more flexibility, plus arrow functions do not have a scope.
When the function is called by the arrow function, the other function will still remain in the correct scope as well, so no need for custom binding
That being said, I can't find dateClick inside the CalendarOptions object, it would be nice to type hint args as well

Prefer arrow function over .bind(this)

---

_docs-v6/intro/initialize-es6.md

I was reading the "Initialize with ES6 Build System" document and expecting to end up with a working example. But I ended up with a blank page. I had to look into other documents to figure out that I need to call render() after creating the Calendar object.

Initialize with ES6: Add calendar.render()

---

_docs-v6/third-party/vue.md

Looks like the Vuex example link was not updated

fix the example link for vuex inside vue.md
